### ISSUE TITLE
xy-select 在特定 web component 组件内使用时会失效

### ISSUE THREAD

**Issue by WangShuXian6** [XboxYan/xy-ui#29]
#### 问题描述
>xy-select 在多层组件嵌套时，点击后不会显示下拉列表。
>查看元素发现是因为在点击后 xy-select 内部的 xy-button 元素的 data-show 属性值被动态赋值后仍然为 false

![image](https://user-images.githubusercontent.com/30850497/62119042-5be35b80-b2f1-11e9-9b77-b1e7b09263ee.png)

>目前这种情况分别出现在我的2个项目内，均为原生项目，均使用 web component.

>由于嵌套非常复杂，暂时写不出复现 demo. 试过简单的嵌套是正常的。

#### 
>版本 1.3.2

#### 可能的原因
>测试发现 xy-select 组件只要放在我写的 web component 组件内,就会失效
>示例 在 LayOut 组件内使用  xy-select 导致  xy-select 下拉无法被激活
```ts
(function () {
  class LayOut extends HTMLElement {
    static get observedAttributes() {
      return ['acitve-title', 'active-sub-title']
    }

    constructor() {
      super()
      this.attachShadow({mode: 'open'})
      this.shadowRoot.innerHTML = `
        <style>
        
        </style>
        
        <div class="wrapper">
          <xy-select>
              <xy-option value="1">Option1</xy-option>
              <xy-option value="2">Option2</xy-option>
              <xy-option value="3">Option3</xy-option>
          </xy-select>
       
        </div>
      `

      this._a = ''
    }

    connectedCallback() {
    }

    disconnectedCallback() {

    }

    attributeChangedCallback(attr, oldVal, newVal) {
      // const attribute = attr.toLowerCase()
      // if (attribute === 'descriptions') {
      //   console.log(1)
      //   this.render(newVal)
      // }
    }

  }

  const FrozenLayOut = Object.freeze(LayOut);
  customElements.define('lay-out', FrozenLayOut);
})()

```

**Comment by XboxYan** [comment]
我回头试试，正打算重构，基于`xy-popover`

**Comment by XboxYan** [comment]
`document`监听`click`下的`ev.target`导致，`xy-popover`同样存在该问题。
现已解决，后面重构了一起更新。

**Comment by WangShuXian6** [comment]
>xy-tab 也有类似的问题

>在 web component 组件内，xy-tab 选中时的下划线不会显示,如下
![image](https://user-images.githubusercontent.com/30850497/62271691-d0daa080-b46b-11e9-946b-342b38cc3581.png)

>在普通  html 里可以显示,如下
![image](https://user-images.githubusercontent.com/30850497/62271714-e4860700-b46b-11e9-8ff2-1067797cc253.png)

**Comment by XboxYan** [comment]
> > xy-tab 也有类似的问题
> 
> > 在 web component 组件内，xy-tab 选中时的下划线不会显示,如下
> > ![image](https://user-images.githubusercontent.com/30850497/62271691-d0daa080-b46b-11e9-946b-342b38cc3581.png)
> 
> > 在普通  html 里可以显示,如下
> > ![image](https://user-images.githubusercontent.com/30850497/62271714-e4860700-b46b-11e9-8ff2-1067797cc253.png)

暂时未重现该问题。
