### ISSUE TITLE
xy-select 聚焦时优先级过高会遮住其他 xy-select 的下拉列表

### ISSUE THREAD

**Issue by WangShuXian6** [XboxYan/xy-ui#32]
#### 演示
![xy-ui](https://user-images.githubusercontent.com/30850497/62375982-2e591500-b572-11e9-96c5-1c964fb810a9.gif)

>点击一个 xy-select 时，鼠标移动至该 xy-select 的第一个下拉列表时，当鼠标在xy-select 和其 下拉列表之间的空白处时，会触发下拉列表下层的 其他 xy-select 的聚焦。

>版本 1.3.4

**Comment by XboxYan** [comment]
`hover`层级问题，下版本更新
