### ISSUE TITLE
请问 Web Components 开发过程中，如何解决写在 js 文件中的 template 提示问题呢？

### ISSUE THREAD

**Issue by YunYouJun** [XboxYan/xy-ui#45]
请问 Web Components 开发过程中，如何解决写在 js 文件中的 template 提示问题呢？
譬如 VS Code 里安装插件写 React JSX 会有标签提示，而看了下您写的代码都是在 js 里直接字符串渲染。
请问像这类似有辅助的提示工具吗？

```js
const template = document.createElement("template");
template.innerHTML = `
<style>
  ...
</style>
`;
```

还是说直接硬写？

**Comment by WangShuXian6** [comment]
```es6-string-html```
```es6-string-css```

>但是不完美，也不是很好用。

**Comment by YunYouJun** [comment]
Thanks.
