### ISSUE TITLE
xy-textarea设置rows不生效

### ISSUE THREAD

**Issue by foreverjcx** [XboxYan/xy-ui#69]

**Comment by XboxYan** [comment]
看了下，这个没有做属性监听，初始化应该没有问题，后续实时更改属性不会生效

**Comment by XboxYan** [comment]
@foreverjcx 已修复

**Comment by foreverjcx** [comment]
@XboxYan 这个初始化的时候也有问题，这个rows一直就是3，需要在attributeChangedCallback里面加上这段： if(name == 'rows' && this.input){
            this.input.setAttribute('rows', newValue);
        }
